//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public long AttendanceDateID { get; set; }
        public int AttendanceWorkerID { get; set; }
        public int AttendanceWorkerStateID { get; set; }
        public int AttendanceWorkerTourID { get; set; }
        public string AttendanceDescription { get; set; }
    
        public virtual Date Date { get; set; }
        public virtual Tour Tour { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual WorkerState WorkerState { get; set; }
    }
}
