//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Changeover
    {
        public int ChangeoverID { get; set; }
        public long ChangeoverDateID { get; set; }
        public int ChangeoverVehicleID { get; set; }
        public int ChangeoverWorkTypeID { get; set; }
        public string ChangeoverDescription { get; set; }
        public int ChangeoverDetachmentID { get; set; }
    
        public virtual Date Date { get; set; }
        public virtual Detachment Detachment { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual WorkType WorkType { get; set; }
    }
}
