//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date
    {
        public Date()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Changeovers = new HashSet<Changeover>();
            this.Works = new HashSet<Work>();
        }
    
        public long DateID { get; set; }
        public System.DateTime DateDate { get; set; }
        public bool DateIsNight { get; set; }
        public string DateDescription { get; set; }
        public int DateDetachmentID { get; set; }
        public bool DateIsClosed { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Detachment Detachment { get; set; }
        public virtual ICollection<Changeover> Changeovers { get; set; }
        public virtual ICollection<Work> Works { get; set; }
    }
}
