//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int UserID { get; set; }
        public Nullable<int> UserWorkerID { get; set; }
        public int UserDetachmentID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserDescription { get; set; }
    
        public virtual Detachment Detachment { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
