//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.Changeovers = new HashSet<Changeover>();
            this.Works = new HashSet<Work>();
        }
    
        public int VehicleID { get; set; }
        public string VehicleNumber { get; set; }
        public string VehicleDescription { get; set; }
        public int VehicleDetachmentID { get; set; }
    
        public virtual Detachment Detachment { get; set; }
        public virtual ICollection<Changeover> Changeovers { get; set; }
        public virtual ICollection<Work> Works { get; set; }
    }
}
