//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Users = new HashSet<User>();
            this.Tours = new HashSet<Tour>();
        }
    
        public int WorkerID { get; set; }
        public string WorkerFirstName { get; set; }
        public string WorkerLastName { get; set; }
        public string WorkerServiceNumber { get; set; }
        public string WorkerSapNumber { get; set; }
        public string WorkerServiceEmail { get; set; }
        public string WorkerPersonalEmail { get; set; }
        public string WorkerServicePhone { get; set; }
        public string WorkerPersonalPhone { get; set; }
        public string WorkerDescription { get; set; }
        public byte[] WorkerPhoto { get; set; }
        public int WorkerDetachmentID { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Detachment Detachment { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Tour> Tours { get; set; }
    }
}
