//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HA.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerState
    {
        public WorkerState()
        {
            this.Attendances = new HashSet<Attendance>();
        }
    
        public int WorkerStateID { get; set; }
        public string WorkerStateName { get; set; }
        public string WorkerStateDescription { get; set; }
        public int WorkerStateDetachmentID { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Detachment Detachment { get; set; }
    }
}
